name: Validate Rumble JSON

on: [pull_request,workflow_dispatch]

jobs:
  validate_rumble:
    name: Validate Rumble JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Validate Rumble JSON with schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./common/data/rumble.schema.json
          json_path_pattern: .*rumble.json$
          send_comment: true
          clear_comments: true
